services:
#    marie_louvres.example:
#        class: Marie\LouvresBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
    BookingManager:
        class: Marie\LouvresBundle\Service\BookingManager